version: "3.3"

services:
  face_checker_server:
    build:
      context: "../face-checker-back"
      dockerfile: "../docker-compose-app-template/docker/server/Dockerfile"
    hostname: "face_checker_server"
    tty: true
  face_checker_nginx:
    build:
      context: "../face-checker-front"
      dockerfile: "../docker-compose-app-template/docker/nginx/Dockerfile"
    hostname: "face_checker_nginx"
    ports:
      - "80:80"
    depends_on:
      - "face_checker_server"